name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Download code
        uses: actions/checkout@v3

      - name: 🟢 Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.20.1

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗 Build project
        run: npm run build